when: 
  event:
    - tag

steps:

  ready-release:
    image: node:20
    commands:
      - apt-get update
      - apt-get install -y zip
      - mkdir -p temp
      - zip -r temp/linux.zip linux
      - zip -r temp/windows.zip windows

  create-release:
    image: woodpeckerci/plugin-release
    settings:
      files:
        - windows/resources/app.asar
        - temp/linux.zip
        - temp/windows.zip
      api_key:
        from_secret: ACCESS_TOKEN
      when:
      event:
        - tag
